### ISSUE TITLE
[Question]How could I know if the intention is for create, update or delete when Reconcile called

### ISSUE THREAD

**Issue by keshin** [kubernetes-sigs/apiserver-builder-alpha#236]
I tried this tool, the code structure is very clear and easy to understand, while I have question when Reconcile of Controller get called.
1. How could I know if is for creating, updating or deletion when the Reconcile get called?
2. If it is updating, how could I get the old value/instance of the resource?

The reason I ask is my controller needs to go different approach with another service in case of creating and updating, while I didn't see a way to distinguish them.

Many thanks.
Keshin

**Comment by pwittrock** [comment]
You really don't want to do this because events maybe batched together.  e.g. a reconcile may see the results of a create and 2 updates.

**Comment by keshin** [comment]
@pwittrock , According to the description of controller in https://kubernetes.io/docs/user-journeys/users/application-developer/foundational/#section-3

> What is the current state of the cluster (X)?
> 
> What is the desired state of the cluster (Y)?
> 
> X == Y ?
> 
> true - Do nothing.
> false - Perform tasks to get to Y, such as starting or restarting containers, or scaling the number of replicas of a given application. Return to 1.

Consider the cases of below:
1. my case needs to have different action for create or update, how could I distinguish that in Reconcile
2. Every time I restart/redeploy the controller, it will pick all of the processed resources into OnAdd func again, how could I know that if Reconcile is the only method I can rely on?
3. According to the api of ResourceEventHandler, the **OnUpdate is also called when a re-list happens, and it will get called even if nothing changed.**, what If my controller doesn't want to do anything if nothing changed from very beginning?

```go
// ResourceEventHandler can handle notifications for events that happen to a
// resource. The events are informational only, so you can't return an
// error.
//  * OnAdd is called when an object is added.
//  * OnUpdate is called when an object is modified. Note that oldObj is the
//      last known state of the object-- it is possible that several changes
//      were combined together, so you can't use this to see every single
//      change. OnUpdate is also called when a re-list happens, and it will
//      get called even if nothing changed. This is useful for periodically
//      evaluating or syncing something.
//  * OnDelete will get the final state of the item if it is known, otherwise
//      it will get an object of type DeletedFinalStateUnknown. This can
//      happen if the watch is closed and misses the delete event and we don't
//      notice the deletion until the subsequent re-list.
type ResourceEventHandler interface {
	OnAdd(obj interface{})
	OnUpdate(oldObj, newObj interface{})
	OnDelete(obj interface{})
}
```
