### ISSUE TITLE
 [Question] How to specifiy short names for a resource?

### ISSUE THREAD

**Issue by yaxinlx** [kubernetes-sigs/apiserver-builder-alpha#249]
[The docs](https://github.com/kubernetes-incubator/apiserver-builder/blob/master/docs/concepts/aggregation.md) mentions a resource can have shortNames, but I didn't found a way to do this in code.

**Comment by yue9944882** [comment]
/triage support

hey @yaxinlx , take the content of `example/pkg/apis/innsmouth/zz_generated.api.register.go` as example, if u want to add short name(s) to that resource, u can simply append a method for its storage like:

```go
func (s *storageDeepOne) ShortNames() []string {
	return []string{"do"}
}
```

**Comment by magicsong** [comment]
@yue9944882 what about "customize Server-side printing", currently , the output of `kubectl get myresource` is quite a few.  BTW, how do find I these `ShortNames()` interface, I cannot find any code include these( I only find some create,update strategies).

**Comment by neosab** [comment]
As a user, it will be great if we can get support for specifying shortnames. Seems like #283 was pretty close, any update on it?

**Comment by yue9944882** [comment]
for now, we can support shortname/catagory by [customizing REST](https://github.com/kubernetes-incubator/apiserver-builder-alpha/blob/master/docs/adding_custom_rest.md) and i added an example by #359. the other pull is breaking underlying api-machinery hierarchy as i reviewed and commented.

alternatively, we can support providing shortnames via resources tag like `// +resource: ....,shortNames=abc` in the type definition.

**Comment by neosab** [comment]
> for now, we can support shortname/catagory by [customizing REST](https://github.com/kubernetes-incubator/apiserver-builder-alpha/blob/master/docs/adding_custom_rest.md) and i added an example by #359. the other pull is breaking underlying api-machinery hierarchy as i reviewed and commented.

I will try this out



> alternatively, we can support providing shortnames via resources tag like `// +resource: ....,shortNames=abc` in the type definition.

That will be nice to have.
