### ISSUE TITLE
Failed to build apiserver due to bazel errors

### ISSUE THREAD

**Issue by WanLinghao** [kubernetes-sigs/apiserver-builder-alpha#351]
I am trying build my own apiserver step by step instructed by :https://github.com/kubernetes-incubator/apiserver-builder-alpha/commits/example-simple
But I ran into unexpected error in step 6, it tells me that I shoud execute  `apiserver-boot build executables --bazel --gazelle --generate=false`
And it ends with errors like:
```
bazel run //:gazelle
Starting local Bazel server and connecting to it...

ERROR: /home/wlh/mywork/go/packages/src/github.com/kubernetes-incubator/apiserver-builder-alpha/WORKSPACE:2:1: name 'http_archive' is not defined
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': error loading package 'external': Could not load //external package
INFO: Elapsed time: 1.413s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
2019/05/17 18:21:56 exit status 1
```
Could anyone help

**Comment by WanLinghao** [comment]
@pwittrock Any thoughts?

**Comment by yue9944882** [comment]
hi @WanLinghao, thanks for reporting this. it's sort of a duplication of #312. bazel build is broken for now for some issue.  please remove the options `--bazel --gazelle` and run again the command. and i'll the revise the guide in a follow-up.
