### ISSUE TITLE
[Feature] Support generic SQL-family storage backend

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-sigs/apiserver-builder-alpha#362]
integrating https://github.com/ibuildthecloud/kvsql unchains us from many etcd maintainence issues. we probably want to provide a generic framework supporting MYSQL, SQLite as storage backends for aggregated apiservers.

**Comment by adohe** [comment]
@pwittrock

**Comment by yue9944882** [comment]
note that the default backend should always be `etcd` to align w/ the general architecture, splitting an optional pass for SQL backend is for saving time and troubles for those developers trying plumbing their existing backends into the kubernetes lifecycle.

**Comment by yue9944882** [comment]
the rancher guys are releasing a new project named `kine` including an etcd-shim and storage-driver. we'll move on after that.

**Comment by yue9944882** [comment]
ref: https://github.com/rancher/k3s/issues/520

**Comment by yue9944882** [comment]
example for integrating SQL storages has been out https://github.com/kubernetes-sigs/apiserver-builder-alpha/tree/master/example/kine
