### ISSUE TITLE
Trying to install using relaese images OR by make install fails.

### ISSUE THREAD

**Issue by rajr0** [kubernetes-sigs/apiserver-builder-alpha#397]
Installation instructions:

    Download the latest release

$ wget https://sigs.k8s.io/apiserver-builder-alpha/releases
...
HTTP request sent, awaiting response... 404 Not Found
2019-08-26 15:01:08 ERROR 404: Not Found.

$ make build
rm -rf *.deb *.rpm *.tar.gz ./release
go run ./cmd/apiserver-builder-release/main.go vendor --version v1.12.alpha.4 --commit a1d139f70f3907e2c05c68f389db901c7c6ea9ef
cp -R -H vendor /home/rraman/go/src/github.com/kubernetes-sigs/apiserver-builder-alpha/release/v1.12.alpha.4/src
cp -R -H pkg /home/rraman/go/src/github.com/kubernetes-sigs/apiserver-builder-alpha/release/v1.12.alpha.4/src/vendor/sigs.k8s.io/apiserver-builder-alpha/pkg
bash -c find /home/rraman/go/src/github.com/kubernetes-sigs/apiserver-builder-alpha/release/v1.12.alpha.4/src/vendor/sigs.k8s.io/apiserver-builder-alpha/pkg -name BUILD.bazel| xargs sed -i='' s'|//pkg|//vendor/sigs.k8s.io/apiserver-builder-alpha/pkg|g'
cp -R -H Gopkg.toml /home/rraman/go/src/github.com/kubernetes-sigs/apiserver-builder-alpha/release/v1.12.alpha.4/src/Gopkg.toml
cp -R -H Gopkg.lock /home/rraman/go/src/github.com/kubernetes-sigs/apiserver-builder-alpha/release/v1.12.alpha.4/src/Gopkg.lock
go run ./cmd/apiserver-builder-release/main.go build --version v1.12.alpha.4
go build -o /home/rraman/go/src/github.com/kubernetes-sigs/apiserver-builder-alpha/release/v1.12.alpha.4/bin/gen-apidocs cmd/vendor/github.com/kubernetes-incubator/reference-docs/gen-apidocs/main.go
go build -o /home/rraman/go/src/github.com/kubernetes-sigs/apiserver-builder-alpha/release/v1.12.alpha.4/bin/client-gen cmd/vendor/k8s.io/code-generator/cmd/client-gen/main.go
go build -o /home/rraman/go/src/github.com/kubernetes-sigs/apiserver-builder-alpha/release/v1.12.alpha.4/bin/conversion-gen cmd/vendor/k8s.io/code-generator/cmd/conversion-gen/main.go
go build -o /home/rraman/go/src/github.com/kubernetes-sigs/apiserver-builder-alpha/release/v1.12.alpha.4/bin/deepcopy-gen cmd/vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go
go build -o /home/rraman/go/src/github.com/kubernetes-sigs/apiserver-builder-alpha/release/v1.12.alpha.4/bin/defaulter-gen cmd/vendor/k8s.io/code-generator/cmd/defaulter-gen/main.go
go build -o /home/rraman/go/src/github.com/kubernetes-sigs/apiserver-builder-alpha/release/v1.12.alpha.4/bin/informer-gen cmd/vendor/k8s.io/code-generator/cmd/informer-gen/main.go
go build -o /home/rraman/go/src/github.com/kubernetes-sigs/apiserver-builder-alpha/release/v1.12.alpha.4/bin/lister-gen cmd/vendor/k8s.io/code-generator/cmd/lister-gen/main.go
go build -o /home/rraman/go/src/github.com/kubernetes-sigs/apiserver-builder-alpha/release/v1.12.alpha.4/bin/openapi-gen cmd/vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go
go build -o /home/rraman/go/src/github.com/kubernetes-sigs/apiserver-builder-alpha/release/v1.12.alpha.4/bin/apiregister-gen cmd/apiregister-gen/main.go
# command-line-arguments
cmd/apiregister-gen/main.go:44:21: cannot use arguments (type *"github.com/kubernetes-sigs/apiserver-builder-alpha/cmd/vendor/k8s.io/gengo/args".GeneratorArgs) as type *"sigs.k8s.io/apiserver-builder-alpha/cmd/vendor/k8s.io/gengo/args".GeneratorArgs in argument to g.Execute
2019/08/26 14:56:55 exit status 2
exit status 1
Makefile:61: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by yue9944882** [comment]
thank you for reporting this. the link became invalid during the latest repo migration. i opened #399 to revise the link. 

> cmd/apiregister-gen/main.go:44:21: cannot use arguments (type *"github.com/kubernetes-sigs/apiserver-builder-alpha/cmd/vendor/k8s.io/gengo/args".GeneratorArgs) as type *"sigs.k8s.io/apiserver-builder-alpha/cmd/vendor/k8s.io/gengo/args".GeneratorArgs in argument to g.Execute

as for your build failure, it seems that it's because the project doesn't locate in correct folders under GOPATH. it should be `$GOPATH/sigs.k8s.io/apiserver-builder-alpha/...` instead of `$GOPATH/github.com/kubernetes-sigs/apiserver-builder-alpha/...`

**Comment by yue9944882** [comment]
yes, i will fix all the broken links in the projects altogether.
