### ISSUE TITLE
Building the container using apiserver-boot build container --image {image} fails

### ISSUE THREAD

**Issue by raushan2016** [kubernetes-sigs/apiserver-builder-alpha#398]
**Environment:**
 OS: Ubuntu 18.04.2 LTS
 apiserver-boot: v1.12.alpha.4

Running `apiserver-boot build container --image raushan2016/apiserver:latest` fails at the docker build step. Although the folder is generated in the path tmp/apiserver-boot-build-container964070301.
If i move this content of the folder to my home directory and try docker build it works but fails with the error 
`E: Opening configuration file /etc/apt/apt.conf.d/01autoremove - ifstream::ifstream (13: Permission denied)`

**Detailed Error** 
`apiserver-boot build container --image raushan2016/apiserver:latest
2019/08/27 02:29:27 Will build docker Image from directory /tmp/apiserver-boot-build-container964070301
2019/08/27 02:29:27 Writing the Dockerfile.
2019/08/27 02:29:27 Building binaries for linux amd64.
2019/08/27 02:29:27 regenerating generated code.  To disable regeneration, run with --generate=false.
/home/raushank/tools/apiserver-builder/bin/apiregister-gen --input-dirs junk.apiserver.example/pkg/apis/... --input-dirs junk.apiserver.example/pkg/controller/...
/home/raushank/tools/apiserver-builder/bin/conversion-gen --input-dirs junk.apiserver.example/pkg/apis/instance/v1beta1 --input-dirs junk.apiserver.example/pkg/apis/instance -o /home/raushank/go/src --go-header-file boilerplate.go.txt -O zz_generated.conversion --extra-peer-dirs k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/conversion,k8s.io/apimachinery/pkg/runtime
/home/raushank/tools/apiserver-builder/bin/deepcopy-gen --input-dirs junk.apiserver.example/pkg/apis/instance/v1beta1 --input-dirs junk.apiserver.example/pkg/apis/instance -o /home/raushank/go/src --go-header-file boilerplate.go.txt -O zz_generated.deepcopy
/home/raushank/tools/apiserver-builder/bin/openapi-gen --input-dirs junk.apiserver.example/pkg/apis/instance/v1beta1 -o /home/raushank/go/src --go-header-file boilerplate.go.txt -i k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/api/resource,k8s.io/apimachinery/pkg/version,k8s.io/apimachinery/pkg/runtime,k8s.io/apimachinery/pkg/util/intstr,k8s.io/api/admission/v1beta1,k8s.io/api/admissionregistration/v1alpha1,k8s.io/api/admissionregistration/v1beta1,k8s.io/api/apps/v1,k8s.io/api/apps/v1beta1,k8s.io/api/apps/v1beta2,k8s.io/api/authentication/v1,k8s.io/api/authentication/v1beta1,k8s.io/api/authorization/v1,k8s.io/api/authorization/v1beta1,k8s.io/api/autoscaling/v1,k8s.io/api/autoscaling/v2beta1,k8s.io/api/autoscaling/v2beta2,k8s.io/api/batch/v1,k8s.io/api/batch/v1beta1,k8s.io/api/batch/v2alpha1,k8s.io/api/certificates/v1beta1,k8s.io/api/coordination/v1beta1,k8s.io/api/core/v1,k8s.io/api/events/v1beta1,k8s.io/api/extensions/v1beta1,k8s.io/api/networking/v1,k8s.io/api/policy/v1beta1,k8s.io/api/rbac/v1,k8s.io/api/rbac/v1alpha1,k8s.io/api/rbac/v1beta1,k8s.io/api/scheduling/v1alpha1,k8s.io/api/scheduling/v1beta1,k8s.io/api/settings/v1alpha1,k8s.io/api/storage/v1,k8s.io/api/storage/v1alpha1,k8s.io/api/storage/v1beta1,k8s.io/client-go/pkg/apis/clientauthentication/v1alpha1,k8s.io/client-go/pkg/apis/clientauthentication/v1beta1,k8s.io/api/core/v1 --report-filename violations.report --output-package junk.apiserver.example/pkg/openapi
/home/raushank/tools/apiserver-builder/bin/defaulter-gen --input-dirs junk.apiserver.example/pkg/apis/instance/v1beta1 --input-dirs junk.apiserver.example/pkg/apis/instance -o /home/raushank/go/src --go-header-file boilerplate.go.txt -O zz_generated.defaults --extra-peer-dirs= k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/conversion,k8s.io/apimachinery/pkg/runtime
/home/raushank/tools/apiserver-builder/bin/client-gen -o /home/raushank/go/src --go-header-file boilerplate.go.txt --input-base junk.apiserver.example/pkg/apis --input instance/v1beta1 --clientset-path junk.apiserver.example/pkg/client/clientset_generated --clientset-name clientset
/home/raushank/tools/apiserver-builder/bin/lister-gen --input-dirs junk.apiserver.example/pkg/apis/instance/v1beta1 -o /home/raushank/go/src --go-header-file boilerplate.go.txt --output-package junk.apiserver.example/pkg/client/listers_generated
/home/raushank/tools/apiserver-builder/bin/informer-gen --input-dirs junk.apiserver.example/pkg/apis/instance/v1beta1 -o /home/raushank/go/src --go-header-file boilerplate.go.txt --output-package junk.apiserver.example/pkg/client/informers_generated --listers-package junk.apiserver.example/pkg/client/listers_generated --versioned-clientset-package junk.apiserver.example/pkg/client/clientset_generated/clientset
2019/08/27 02:29:57 CGO_ENABLED=0
2019/08/27 02:29:57 GOOS=linux
2019/08/27 02:29:57 GOARCH=amd64
go build -o /tmp/apiserver-boot-build-container964070301/apiserver cmd/apiserver/main.go
go build -o /tmp/apiserver-boot-build-container964070301/controller-manager cmd/manager/main.go
2019/08/27 02:30:07 Building the docker Image using /tmp/apiserver-boot-build-container964070301/Dockerfile.
2019/08/27 02:30:07 docker build -t raushan2016/apiserver:latest /tmp/apiserver-boot-build-container964070301
unable to prepare context: path "/tmp/apiserver-boot-build-container964070301" not found
2019/08/27 02:30:07 command failed exit status 1
Makefile:16: recipe for target 'docker-build' failed
make: *** [docker-build] Error 1`

**Comment by yue9944882** [comment]
it's always working fine in my local environment. but it's probably related with the incorrect setup of docker registry, are you using the official?
