### ISSUE TITLE
Running API server in cluster results in controller container failure due to missing CRD.

### ISSUE THREAD

**Issue by raushan2016** [kubernetes-sigs/apiserver-builder-alpha#408]
Running the api-server in a cluster using the [steps ](https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/docs/running_in_cluster.md). Results in below error in controller container.

`{"level":"info","ts":1567048466.3174245,"logger":"entrypoint","msg":"setting up client for manager"}
{"level":"info","ts":1567048466.3177454,"logger":"entrypoint","msg":"setting up manager"}
{"level":"info","ts":1567048466.5520928,"logger":"entrypoint","msg":"Registering Components."}
{"level":"info","ts":1567048466.5521219,"logger":"entrypoint","msg":"setting up scheme"}
{"level":"info","ts":1567048466.5522196,"logger":"entrypoint","msg":"Setting up controller"}
{"level":"info","ts":1567048466.5522645,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"managedinferenceresource-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1567048466.5523,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":{"Group":"instance.mir.azureml.k8.io","Kind":"ManagedInferenceResource"},"error":"no matches for kind "ManagedInferenceResource" in version "instance.mir.azureml.k8.io/v1beta1"","stacktrace":"sample-api-server/vendor/github.com/go-logr/zapr.(*zapLogger).Error

I tried generating the CRD using the `go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go crd --output-dir=config/crds` same as kubebuilder but it failed with the error

`panic: Cannot get version for unversioned type sample-api -server/pkg/apis/foobar.abc
goroutine 1 [running]:
sample-api-server/vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse.GetVersion(0xc015ce1c30, 0xc00028249c, 0x8, 0xc015d74090, 0x57007f86606bf008)`

**Comment by yue9944882** [comment]
@raushan2016 the error is suggesting that your apiserver isn't started/registered in the cluster. can you confirm if the apiserver container is correctly running?

**Comment by raushan2016** [comment]
Yes the api-server is running fine with the log `I0829 03:16:03.434742       1 secure_serving.go:116] Serving securely on [::]:443`

**Comment by yue9944882** [comment]
what do you get running `kubectl --raw="/apis/instance.mir.azureml.k8.io/v1beta1"`?

**Comment by raushan2016** [comment]
You meant `kubectl get --raw="/apis/instance.mir.azureml.k8.io/v1beta1"` 
It gives error `Error from server (ServiceUnavailable): the server is currently unable to handle the request`

`kubectl api-versions` does give this list
certificates.k8s.io/v1beta1
coordination.k8s.io/v1beta1
events.k8s.io/v1beta1
extensions/v1beta1
instance.mir.azureml.k8.io/v1beta1
metrics.k8s.io/v1beta1
networking.k8s.io/v1
policy/v1beta1
rbac.authorization.k8s.io/v1

**Comment by yue9944882** [comment]
it seems that network between your aggregated-apiserver and kube-apiserver is probably broken. what's output of `kubectl describe apiservice v1beta1.instance.bar.foo.k8.io`?

**Comment by raushan2016** [comment]
Got it working now. I was trying to integrated kustomize and used namespace in kustomization.yaml. This causes things to be created in a new namespace but the `APIService` service was pointing to `default` namespace.

So there is no need for CRD generation for API server?

**Comment by yue9944882** [comment]
> So there is no need for CRD generation for API server?

yes, AA(APIServer Aggregation) is another way to extend kubernetes other than CRD. https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/

**Comment by raushan2016** [comment]
I had to manually create the CRD yaml file and install in the cluster to get it working. Is this a known issue.

**Comment by raushan2016** [comment]
Also i see error in the api-server container
I0829 21:03:37.067752       1 log.go:172] http: TLS handshake error from 10.244.0.5:52670: remote error: tls: bad certificate
I0829 21:03:37.067752       1 log.go:172] http: TLS handshake error from 10.244.0.5:52670: remote error: tls: bad certificate
I0829 21:06:31.362722       1 log.go:172] http: TLS handshake error from 10.244.0.5:60988: remote error: tls: bad certificate
I0829 21:06:31.362722       1 log.go:172] http: TLS handshake error from 10.244.0.5:60988: remote error: tls: bad certificate
I0829 21:06:31.510772       1 log.go:172] http: TLS handshake error from 10.244.0.5:32774: remote error: tls: bad certificate
I0829 21:06:31.510772       1 log.go:172] http: TLS handshake error from 10.244.0.5:32774: remote error: tls: bad certificate

**Comment by raushan2016** [comment]
Got it working :)
