### ISSUE TITLE
file generated by `apiserver-boot create` cannot compile

### ISSUE THREAD

**Issue by aylei** [kubernetes-sigs/apiserver-builder-alpha#437]
Follow up: https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/436#discussion_r341859066

The code generated by apiserver-boot should also be updated to be compatible with the `1.16` kubernetes dependencies.

cc @cofyc

**Comment by yue9944882** [comment]
i will schedule a release for 1.16 i.e. v.1.16.alpha.0 very soon, before that we can build ur own release by running `make install` from the project root. that will be a workaround for the issue.

-- thanks, min
