### ISSUE TITLE
Upgrade rules_go and bazel settings to make bazel build work

### ISSUE THREAD

**Issue by weixiao-huang** [kubernetes-sigs/apiserver-builder-alpha#449]
Current `rules_go`'s version is too old, and the latest `rules_go` is `v0.20.3`. Also, since `http_archive` should be imported by using

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
```

the codes in `WORKSPACE` is too old to execute. They need to upgrade.

**Comment by yue9944882** [comment]
sadly the bazel integration isnt refreshed for a period of time (@pwittrock and other googler folks opened the box but it seems they are fading the bazel support from other related projects as well). we're not using bazel in production either so know little about it.. plz feel free to bump the bazel setups by sending a pull. thanks

**Comment by weixiao-huang** [comment]
I've open https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/451 to upgrade bazel and rules_go ONLY for `cmd` directory. If there's no problem, I can extend it to support other directories

**Comment by weixiao-huang** [comment]
Close this issue since #451 has been merged
