### ISSUE TITLE
list 404 urls

### ISSUE THREAD

**Issue by CriaHu** [kubernetes-sigs/apiserver-builder-alpha#463]
1./CONTRIBUTING.md  
~~https://git.k8s.io/community/contributors/guide/contributor-cheatsheet.md~~
2./docs/adding_custom_rest.md
docs/adding_custom_rest.md
 ~~https://sigs.k8s.io/apiserver-builder-alpha/blob/master/docs/adding_resources.md~~
3./docs/adding_custom_rest.md 
~~https://sigs.k8s.io/apiserver-builder-alpha/blob/master/docs/adding_subresources.md~~
4./docs/adding_custom_rest.md 
https://sigs.k8s.io/apiserver-builder-alpha/issues/92
5./docs/compare_with_kubebuilder.md https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md
6./docs/creating_an_api_server.md
https://sigs.k8s.io/apiserver-builder-alpha/blob/master/docs/getting_started.md
7./docs/tools_user_guide.md
~~https://sigs.k8s.io/apiserver-builder-alpha/blob/master/docs/installing.md~~
8./docs/building_docs.md
 https://github.com/kubernetes-incubator/reference-docs/blob/master/gen-apidocs/generators/config.yaml

**Comment by Skillshot** [comment]
Is anybody going to fix this broken urls?
It has been a long time for now already.

**Comment by yue9944882** [comment]
added to my list, will take a shot this week or next.
