### ISSUE TITLE
use go.{mod} instead of Gopkg.{toml,lock}

### ISSUE THREAD

**Issue by weixiao-huang** [kubernetes-sigs/apiserver-builder-alpha#465]
Now go modules have been widely used in lots of projects. Also the [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) has used go modules in its project repo and also used go modules in its generated codes. So I recommend change dep into go modules both in this project and the generated codes.
By using go modules, the `vendor.tar.gz` may be no need to be packaged into the release tar.gz since go modules supports a `go mod vendor` to generate vendor dir.

**Comment by yue9944882** [comment]
yeah, tho am a bit surprised kubebuilder has completed migrated to gomod instead of keep them in parallel for several releases. this repo will always be following up actions of kubebuilder so i see the ponit valid to me. will consider this at 1.17.x releases. and btw this requires this repo to follow semver taggings which is a prerequisite action item

**Comment by weixiao-huang** [comment]
I think that following semver taggings is valid. I guess the current version `v1.16.alpha.0` means that it may match `kubernetes-1.16.0`. This version match may be unnecessary, for we can get kubernetes version in `scripts/print-workspace-status.sh` or using a better way.

**Comment by yue9944882** [comment]
>  I guess the current version v1.16.alpha.0 means that it may match kubernetes-1.16.0. 

the major and minor bits will be following the kubernetes' version while the patch version doesnt have to align. it will increment per releases starting from 0.

i will file a new release this week or next. that makes it `v1.16.alpha.1`

**Comment by EronWright** [comment]
For those following the Getting Started guide and getting a build error when using Go 1.13+, you'll probably stumble onto this page when you ask yourself why `go.mod` isn't being used yet.   The solution that worked for me was to set `GO111MODULE` to `off`.

**Comment by weixiao-huang** [comment]
> For those following the Getting Started guide and getting a build error when using Go 1.13+, you'll probably stumble onto this page when you ask yourself why `go.mod` isn't being used yet. The solution that worked for me was to set `GO111MODULE` to `off`.

This is because that if we get go.mod from Gopkg.lock, the version of k8s will be upgrade to 1.17. So we should add replace to lock k8s's version to 1.16.

For solving these problems, I open https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/473 for using go modules.

**Comment by VitaliyShevchenko** [comment]
hey guys,
I saw there are a couple of PRs related to supporting go modules in this project.
@yue9944882 when do you expect to release this functionality?

**Comment by yue9944882** [comment]
@VitaliyShevchenko moving completely to go mod is planned in the very next release i.e. `v1.17.0`. but this will make bring some break changes to the command-line toolings. e.g. the `//+go:generate go run ./vendor/.../` annotations wont work any more. additionally the lastest release `v.1.16.2` is already supporting go mod in a way.

**Comment by VitaliyShevchenko** [comment]
Great! It is nice to read that.

@yue9944882 if you need some help, you can ping me :)
