### ISSUE TITLE
DefaultingFunction :  undefined: <ResourceType>SchemeFns

### ISSUE THREAD

**Issue by Young-china** [kubernetes-sigs/apiserver-builder-alpha#470]
Hi ,

I upgrade my apiserver-builder-alpha  from a low version to `v1.16.alpha.1`,  but the DefaultingFunction report an error: `undefined: MachineSchemeFns`

I followed this [doc](https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/ef5d9b9c01aaa562ce3edc2724fd5d0ed0c8fa2e/docs/concepts/api_building_overview.md#create) to write my code :

```
// DefaultingFunction sets default Machine field values
func (MachineSchemeFns) DefaultingFunction(o interface{}) {
	obj := o.(*Machine)

	// Custom Defaulting logic here
}
```

**Comment by yue9944882** [comment]
the doc is out-of-date, i will refresh it later this week. as for defaulting, plz follow the examples at https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/example/basic/pkg/apis/miskatonic/v1beta1/defaults.go. which is aligning w/ the implementation of kubernetes/kubernetes
