### ISSUE TITLE
Informative Kubectl Printing

### ISSUE THREAD

**Issue by VitaliyShevchenko** [kubernetes-sigs/apiserver-builder-alpha#475]
Hey!

Guys, do you expect to support informative kubectl printing? 
I saw there is `additionalPrinterColumns` property, that we can use to define custom columns, but how can we do the same using your lib? 
Is there any way to implement my custom server-side printing?

Thanks!

**Comment by yue9944882** [comment]
the equal way to support customized printing like `additionalPrinterColumns` is [customizing REST](https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/docs/adding_custom_rest.md) for specific resource. and you can also find code examples in this project:

https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/example/basic/pkg/apis/miskatonic/student_rest.go#L74-L95

**Comment by Skillshot** [comment]
> the equal way to support customized printing like `additionalPrinterColumns` is [customizing REST](https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/docs/adding_custom_rest.md) for specific resource and override the field `TableConvertor`. and you can also find code examples in this project:
> 
> https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/example/basic/pkg/apis/miskatonic/student_rest.go#L74-L95

Thank you for help.
