### ISSUE TITLE
CGO is disabled by default

### ISSUE THREAD

**Issue by VitaliyShevchenko** [kubernetes-sigs/apiserver-builder-alpha#478]
Hi! 

I'm using [go-sqlite3 lib](http://mattn.github.io/go-sqlite3/) to interact with SQLite DB from the application. 
At the same time, I'm using the apiserver-boot script to build docker image `apiserver-boot build container --image image_name`. Since the `go-sqlite3` is using C code, I need to set `CGO_ENABLED=1`, but it's hardcoded as `CGO_ENABLED=0` inside [the script](https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/cmd/apiserver-boot/boot/build/build_executables.go#L167).

Is there a way to provide `CGO_ENABLED=1` from outside? Probably, do you have any suggestions on how to fix this?

Thanks!

**Comment by yue9944882** [comment]
mmm it should override the CGO option if it already exists in the env-vars.. will send a pull to make it override'ble
