### ISSUE TITLE
Cannot use kubectl get my rest apiservice

### ISSUE THREAD

**Issue by xjtustt** [kubernetes-sigs/apiserver-builder-alpha#480]
I follow [this guide](https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/docs/adding_custom_rest.md) to create my own apiservice. 
After thatI can use `curl` to access my service via "apis/mygroup.my-domain/v1/meteringreports". But when I want to use kubectl to get the meteringreports list, I can see this output:
```
NAME   AGE
       <unknown>
       <unknown>
```
I added a `-v=8` to see log details and found an error that said:
`I0222 00:50:05.781270    8580 table_printer.go:43] Unable to decode server response into a Table. Falling back to hardcoded types: attempt to decode non-Table object into a v1beta1.Table`

How to make kubectl display correctly?

**Comment by VitaliyShevchenko** [comment]
I think you have to set `metav1.ObjectMeta.Name` for response in `List` method of `meteringreports` kind. Also, you can try to set `metav1.ObjectMeta.CreationTimestamp` as well. After that, you should be able to see at least `Name` after `kubectl get meteringreports`.

BTW, I saw a similar issue in the k8s. Here is [a PR (https://github.com/kubernetes/kubernetes/pull/85174/files) with fixes.

**Comment by xjtustt** [comment]
@VitaliyShevchenko Thank you, your solution solves my problem.

**Comment by VitaliyShevchenko** [comment]
No problem! You are welcome.

**Comment by xjtustt** [comment]
@VitaliyShevchenko Sorry I found another issue about the output column template.
My resource Report is a namespace scoped resource. So I have the requirement to show reports in all namespaces.
I don't know where to define the default output column, my output only contains "NAME" and "AGE". I want to add a "NAMESPACE" column when user use "--all-namespaces" like what "kubectl get all po --all-namespaces" shows.
Thank you again.
