### ISSUE TITLE
How to get namespace value for my custom REST request?

### ISSUE THREAD

**Issue by xjtustt** [kubernetes-sigs/apiserver-builder-alpha#481]
I added a new custom REST rest resource `Report` and this is a namespaced api.
I want to use the namespace value in the List() and Get() method of the report_rest.go file.
For example, when I use `kubectl get reports -v=8` I can see the request url is
`https://host-name:6443/apis/mygroup.mydomain/v1/namespaces/default/reports`, I want to use the namespace value(default) in the List/Get method.  But I cannot find the namespace informations from the parameters `context.Context` and `k8s.io/apimachinery/pkg/apis/meta/v1/ListOptions(GetOptions)`.

Can anyone help me about this?

**Comment by VitaliyShevchenko** [comment]
When you are building your `config/apiserver.yaml`, using:
```apiserver-boot build config --name <servicename> --namespace <namespace to run in> --image <image to run>``` command. You have to provide **--namespace <namespace to run in>** argument, so basically you know in what namespace your custom resource is created.
If you take a look at your `config/apiserver.yaml`, you notice, that every resource here is created in the namespace, which you provided. 
So, I don't understand why do you need to take it from somewhere, if you already know it and you created everything in this namespace :)

**Comment by VitaliyShevchenko** [comment]
The other option is to get the namespace from request:
```
request.NamespaceFrom(ctx)
```

**Comment by xjtustt** [comment]
> The other option is to get the namespace from request:
> 
> ```
> request.NamespaceFrom(ctx)
> ```

That's what I wanted, thank you @VitaliyShevchenko !
