### ISSUE TITLE
Error Unresolved type in apiserver-builder-alpha\example\basic\pkg\apis\miskatonic

### ISSUE THREAD

**Issue by liabio** [kubernetes-sigs/apiserver-builder-alpha#502]
![image](https://user-images.githubusercontent.com/21979752/82107080-92db0e80-9757-11ea-9acd-8d8c394acd45.png)
Unresolved type 'StudentComputer' 、NewStudentRegistry()、StudentRegistry

Unresolved type 'UniversityRegistry' 、UniversityCampus etc..

**Comment by yue9944882** [comment]
these code are supposed to be generated. run `apiserver-boot build generated` inside specific example project should work
