### ISSUE TITLE
question of apiserver-boot binary

### ISSUE THREAD

**Issue by smartkuk** [kubernetes-sigs/apiserver-builder-alpha#507]
I have a question.

I want to change the Kubernetes version of the extension api server and controller manager source I made,
To do this, do I need to download the apiserver-boot binary file for each version of Kubernetes, give the generated option, and generate code?
Or is there a guide document on this?

**Comment by yue9944882** [comment]
https://github.com/kubernetes-sigs/apiserver-builder-alpha#guides

i believe the guides on the README page will help

**Comment by smartkuk** [comment]
> https://github.com/kubernetes-sigs/apiserver-builder-alpha#guides
> 
> i believe the guides on the README page will help

I read the guides and made my own api extension server.

But I want to create my own api extension server per kubernetes versions(1.16, 1.17, ...).

So I write my question on this repository issue.

Thanks

**Comment by yue9944882** [comment]
@smartkuk mmm.. as far as i know, api extension apiserver's version is independent from kubernetes' version. e.g. an 1.16 api extension apiserver will work in 1.18 kubernetes cluster.
