### ISSUE TITLE
Add new subresource

### ISSUE THREAD

**Issue by smartkuk** [kubernetes-sigs/apiserver-builder-alpha#509]
Hello~

Currently, I have implemented both api extension server and controller-manager. These modules are configured to run outside of Kubernetes cluster.

The created resource name is Application, I tried to follow the documentation([adding subresource]) to add the scale sub resource to it.

The purpose of creating this resource is to use the following command.

```shell
$ kubectl scale --replicas=2 applications testapp
```

```go
Error: unable to get openapi models: no kind "Scale" is registered for version "autoscaling/v1" in scheme "sigs.k8s.io/apiserver-builder-alpha/pkg/builders/scheme.go:26"
```
The above error occurs when starting the api server.

***I think it's a problem in the content below, but I don't know how to fix it.*** (My question)
```go
func (r *ApplicationScaleREST) GroupVersionKind(containingGV schema.GroupVersion) schema.GroupVersionKind {
	return autoscalingv1.SchemeGroupVersion.WithKind("Scale")
}
```

subresource creation was added using the following command.

```sh
$ apiserver-boot create subresource --subresource scale --group smart --version v1 --kind Application
```

current version of apiserver-boot binary is:
```sh
apiserver-boot version
I0630 11:25:22.092117    3332 version.go:57] Version: version.Version{ApiserverBuilderVersion:"v1.16.alpha.2", KubernetesVendor:"kubernetes-1.16.0", GitCommit:"fbc6092eb4d7e58d690516620653fe5e34d194ac", BuildDate:"2020-03-11-18:33:45", GoOs:"darwin", GoArch:"amd64"}
```

[adding subresource]: https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/docs/adding_subresources.md

**Comment by smartkuk** [comment]
I did this experiment, but the phenomenon is unusual.
If set to ApplicationScale string as below source, both api extension server and controller manager started.

```go
func (r *ApplicationScaleREST) GroupVersionKind(containingGV schema.GroupVersion) schema.GroupVersionKind {
    return containingGV.WithKind("ApplicationScale")
}
```

When the scale command is sent, the deployment responds and actually works, but the result of executing the kubectl command produces the following error.

```sh
$ kubectl scale --replicas=2 applications testapp
error: no kind "ApplicationScale" is registered for version "smart.smartfactory.io/v1" in scheme "k8s.io/client-go/scale/util.go:146"
```

Help me~

**Comment by smartkuk** [comment]
additional description!, my subresource is :

```go
// +subresource-request
type ApplicationScale autoscalingv1.Scale
```

I removed generated sources and changed.

**Comment by yue9944882** [comment]
> func (r *ApplicationScaleREST) GroupVersionKind(containingGV schema.GroupVersion) schema.GroupVersionKind {
	return autoscalingv1.SchemeGroupVersion.WithKind("Scale")
}

i believe the code above is correct for adding scale subresource.

> Error: unable to get openapi models: no kind "Scale" is registered for version "autoscaling/v1" in scheme "sigs.k8s.io/apiserver-builder-alpha/pkg/builders/scheme.go:26"

however, the complaining error is suggesting that the Scale subresource is not properly registered. can you try workaround by registerring the scale subresource manually by e.g. :

```go
import "sigs.k8s.io/apiserver-builder-alpha/pkg/builders"
...
autoscalingv1.AddToScheme(builders.Scheme)
```

**Comment by yue9944882** [comment]
i just opened https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/510 to help get rid of the error. the suggested code in my previous comment should also work as a prompt workaround

**Comment by smartkuk** [comment]
Thank you for answer~

I add some codes by your comment. But I have some error like this

```go
// In my scale_application_rest.go
import (
    // ...
    clientscale "k8s.io/client-go/scale/scheme/autoscalingv1"
    "sigs.k8s.io/apiserver-builder-alpha/pkg/builders"
    // ...
)

// I made it private init()
func init() {
    fmt.Println("init for clientscale.AddToScheme(builders.Scheme)")
    clientscale.AddToScheme(builders.Scheme)
}
```

The above code have compile error: ***cannot use builders.Scheme (variable of type *runtime.Scheme) as *runtime.Scheme value in argument to clientscale.AddToScheme***

How to convert these scheme, Is there a convert util???
Can I convert Scheme to Scheme by implementing?

**Comment by yue9944882** [comment]
> cannot use builders.Scheme (variable of type *runtime.Scheme) as *runtime.Scheme value in argument to

mmm.. i can't find any clue from the error, can you refer to the change by https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/510?

**Comment by smartkuk** [comment]
It seems that I have struggled for a long time and solved the related problem, but I am not sure, so I write again here.
***Can you confirm that the process I did is right?***
I made the scale command work on my resource with the following process.

* STEP 1.

```sh
$ apiserver-boot create subresource --subresource scale --group smart --version v1 --kind Application
```

* STEP 2.

```go
// In my scale_application_types.go file
...
import autoscalingv1 "k8s.io/api/autoscaling/v1"
...
// automatically generated ApplicationScale struct source code => autoscalingv1.Scale
type ApplicationScale autoscalingv1.Scale
```

* STEP 3.

Implement functions such as Create, Update, and Get in the scale_application_rest.go file

* STEP 4.

```go
// Implement the follow functions in scale_application_rest.go
...
import autoscalingv1 "k8s.io/api/autoscaling/v1"
...

func (r *ApplicationScaleREST) New() runtime.Object {
	return &autoscalingv1.Scale{}
}

func (r *ApplicationScaleREST) GroupVersionKind(containingGV schema.GroupVersion) schema.GroupVersionKind {
	return autoscalingv1.SchemeGroupVersion.WithKind("Scale")
}

func init() {
	register(builders.Scheme)
}

func register(scheme *runtime.Scheme) {
	scheme.AddKnownTypes(autoscalingv1.SchemeGroupVersion, &autoscalingv1.Scale{})
}
```

After implementing as above and executing as follows, my own resource worked with kubectl scale command. Is this correct implementation? Are there any other sample projects you can reference?

```sh
$ kubectl scale --replicas=2 applications bxmdemo
application.smart.smartfactory.io/bxmdemo scaled
```

**Comment by yue9944882** [comment]
@smartkuk i think so. and i had similar solution for our internal projects, it will be working as expected. plz feel free to open issues on any question.

**Comment by smartkuk** [comment]
> @smartkuk i think so. and i had similar solution for our internal projects, it will be working as expected. plz feel free to open issues on any question.

Thanks for the comments.
Using apiserver-builder-alpha to create a Kubernetes extended API server and controller manager is too hard.
I'm glad you helped me. Thanks again.
Maybe I will continue to ask questions through issues
