### ISSUE TITLE
Gengo gets extremely slower on go mod projects, migrating to controller-tools will ease the pain

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-sigs/apiserver-builder-alpha#517]

**Comment by clarkmcc** [comment]
Noticing a significant amount of time and resource to run `apiserver-boot build generated`. What is the solution here?

**Comment by yue9944882** [comment]
@clarkmcc now we're pruning all generators except for `deepcopy-gen` which can be provided by `controller-tools`. the [apiserver-runtime](https://github.com/kubernetes-sigs/apiserver-runtime/blob/main/sample/pkg/apis/sample/v1alpha1/flunders.go) is supposed to replace the old generators.

**Comment by yue9944882** [comment]
note that the `build generated` command is already removed on the master branch

**Comment by clarkmcc** [comment]
@yue9944882 Thanks, where can I go to read more/stay up to date about the progress and changes on that?

**Comment by yue9944882** [comment]
@clarkmcc still working on it. there will be more documentation as soon as the new release is out.
