### ISSUE TITLE
Storage layer scaffolding for aggregated apiserver

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-sigs/apiserver-builder-alpha#520]
in order to assist developers to build aggregated apiserver upon different storage persistent layers quick and easily, we will provide a set of pre-built storage layer implementation for several commonly-used storage backends:

- [ ] Mysql/PGsql
- [ ] ElasticSearch
- [ ] Git
- [ ] Filepath
- [ ] MongoDB

**Comment by weixiao-huang** [comment]
How about supporting mongoDB, which is a popular NoSQL and may be used in many projects

**Comment by yue9944882** [comment]
@weixiao-huang sgtm, i will start w/ one low-hanging fruit like Mysql and we will see how that goes..

**Comment by clarkmcc** [comment]
I would be happy to take on the MongoDB implementation if needed, I have some background with that product.
