### ISSUE TITLE
Field selectors on generated resources

### ISSUE THREAD

**Issue by clarkmcc** [kubernetes-sigs/apiserver-builder-alpha#537]
I'm getting the following error when doing a `List` using field selectors. Is it possible to add support for additional field selectors on resource types that I've created?

```sh
"spec.source" is not a known field selector: only "metadata.name", "metadata.namespace"
```

**Comment by VitaliyShevchenko** [comment]
yeah, that's possible.
you can use `builders.Scheme.AddFieldLabelConversionFunc` methods to add more needed labels.
You need to pass group version of the resource and a function...
here is an example: https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/example/basic/pkg/apis/olympus/v1beta1/register.go#L13
