### ISSUE TITLE
apiserver-boot build container contains too much magic

### ISSUE THREAD

**Issue by drewwells** [kubernetes-sigs/apiserver-builder-alpha#544]
This command needs to be decomposed. It currently regenerates all the autogen code, stamps out a dockerfile, builds apiserver and the controller. This is great for novice user, but does not lend itself to advanced cases. Most importantly, the dockerfile itself should checked into code so users can change the base image and add their own tools to the dockerfile. 

Use case: I want to create a CICD job to create the build image. The config is already generated and I want to change the base image used in the docker image. The CICD job fails b/c apiserver-boot does not work with non-GOPATH go modules and the Dockerfile is not available for tinkering. Now I need to write my own set of steps outside of the toolkit to do these.

**Comment by yue9944882** [comment]
> This command needs to be decomposed. It currently regenerates all the autogen code, stamps out a dockerfile, builds apiserver and the controller.

@drewwells thank you for reporting this and i agree so. in the next release the apiserver-boot command will be merely doing the project initialization and scaffolding (one-time code-generation) and leave the developers to edit the generated codes. as for generators, we're removing them from this project and instead leveraging (controller-tools)[https://github.com/kubernetes-sigs/controller-tools] to a minimal code-generation which is way faster than the current.

> The CICD job fails b/c apiserver-boot does not work with non-GOPATH go modules and the Dockerfile is not available for tinkering. 

as for the non-GOPATH module support, it's actually blocked on the progress of removing generators mentioned above b/c the apiserver-boot commands will look into the GOPATH and those required code-generator binaries from `$GOPATH/bin/`. i think we will be fixing it in the next release as well.

**Comment by drewwells** [comment]
Sounds good 👍 . Can this issue be closed or does it need to be used as reference for the mentioned work?
