### ISSUE TITLE
New release coming?

### ISSUE THREAD

**Issue by drewwells** [kubernetes-sigs/apiserver-builder-alpha#546]
https://github.com/kubernetes-sigs/apiserver-builder-alpha/compare/v1.18.0...master

There's a decent number of changes since 0.18.0. Some of the examples like non-etcd will build easier with go.mod if there's a release. Is a release planned soon?

```
non-etcd git:(master) ✗ go run cmd/apiserver/main.go     
go: finding module for package sigs.k8s.io/apiserver-builder-alpha/example/non-etcd/plugin/admission/install
cmd/apiserver/main.go:32:2: module sigs.k8s.io/apiserver-builder-alpha@latest found (v1.18.0, replaced by ../../../apiserver-builder-alpha), but does not contain package sigs.k8s.io/apiserver-builder-alpha/example/non-etcd/plugin/admission/install
```

**Comment by yue9944882** [comment]
@drewwells yeah there will be a new release very soon, we're sort of delayed b/c of prepping the next kubecon. we're hopefully seeing it by the end of october!
