### ISSUE TITLE
suite_test overrides provided AggregatedAPIServerFlags

### ISSUE THREAD

**Issue by drewwells** [kubernetes-sigs/apiserver-builder-alpha#557]
It's not possible to override the server flags to local aggregate apiserver with the test framework. The pkg/test/suite is gone now, so I'm not sure where this bug belongs anymore. apiserver-runtime?

**Comment by yue9944882** [comment]
yes, the testing framework will also be moving to the runtime, leaving the necessary code-generation for scaffolding in this repo.
