### ISSUE TITLE
[Bug]`example/kine` and `example/podexec` cannot be successfully constructed

### ISSUE THREAD

**Issue by l-qing** [kubernetes-sigs/apiserver-builder-alpha#568]
Only `example/basic` works.

# `example/kine` failed
```
╭─xx@xx ~/go/src/sigs.k8s.io/apiserver-builder-alpha/example/kine ‹master*›
╰─$ apiserver-boot build executables
I1119 15:46:44.620346   22143 build_executables.go:179] CGO_ENABLED=0
I1119 15:46:44.620486   22143 build_executables.go:189] go build -o bin/apiserver cmd/apiserver/main.go
# sigs.k8s.io/apiserver-builder-alpha/example/kine/pkg/apis/mysql/v1
pkg/apis/mysql/v1/tiger_types.go:60:5: cannot use &Tiger literal (type *Tiger) as type runtime.Object in assignment:
        *Tiger does not implement runtime.Object (missing DeepCopyObject method)
pkg/apis/mysql/v1/tiger_types.go:61:5: cannot use &Tiger literal (type *Tiger) as type "sigs.k8s.io/apiserver-runtime/pkg/builder/resource".Object in assignment:
        *Tiger does not implement "sigs.k8s.io/apiserver-runtime/pkg/builder/resource".Object (missing DeepCopyObject method)
pkg/apis/mysql/v1/tiger_types.go:62:5: cannot use &TigerList literal (type *TigerList) as type "sigs.k8s.io/apiserver-runtime/pkg/builder/resource".ObjectList in assignment:
        *TigerList does not implement "sigs.k8s.io/apiserver-runtime/pkg/builder/resource".ObjectList (missing DeepCopyObject method)
pkg/apis/mysql/v1/tiger_types.go:73:9: cannot use &Tiger literal (type *Tiger) as type runtime.Object in return argument:
        *Tiger does not implement runtime.Object (missing DeepCopyObject method)
pkg/apis/mysql/v1/tiger_types.go:77:9: cannot use &TigerList literal (type *TigerList) as type runtime.Object in return argument:
        *TigerList does not implement runtime.Object (missing DeepCopyObject method)
pkg/apis/mysql/v1/tiger_types.go:92:5: cannot use &Tiger literal (type *Tiger) as type "sigs.k8s.io/apiserver-runtime/pkg/builder/resource".ObjectWithStatusSubResource in assignment:
        *Tiger does not implement "sigs.k8s.io/apiserver-runtime/pkg/builder/resource".ObjectWithStatusSubResource (missing DeepCopyObject method)
pkg/apis/mysql/v1/tiger_types.go:100:8: impossible type assertion:
        *Tiger does not implement "sigs.k8s.io/apiserver-runtime/pkg/builder/resource".ObjectWithStatusSubResource (missing DeepCopyObject method)
F1119 15:46:48.040681   22143 build_executables.go:194] exit status 2
```

# `example/podexec` failed
```
╭─xx@xx ~/go/src/sigs.k8s.io/apiserver-builder-alpha/example/podexec ‹master*›
╰─$ apiserver-boot build executables
I1119 15:53:06.932434   23800 build_executables.go:179] CGO_ENABLED=0
I1119 15:53:06.932612   23800 build_executables.go:189] go build -o bin/apiserver cmd/apiserver/main.go
go: finding module for package sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server
cmd/apiserver/main.go:27:2: module sigs.k8s.io/apiserver-builder-alpha@latest found (v1.18.0, replaced by ../../../apiserver-builder-alpha), but does not contain package sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server
F1119 15:53:08.174624   23800 build_executables.go:194] exit status 1
```

# Env
## Version v2.0.0-alpha.0
apiserver-builder-alpha commit: c1e3ccc445efb29dd9f7efff107c2bd059b3efd3
go version: go1.15.5 linux/amd64
uname: Linux xx 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
apiserver-boot version:  Version: version.Version{ApiserverBuilderVersion:"v2.0.0-alpha.0", KubernetesVendor:"kubernetes-1.19.2", GitCommit:"v2.0.0-alpha.0", BuildDate:"2020-11-04-21:20:28", GoOs:"linux", GoArch:"amd64"}

## Version 1.18.0 failed to build too.
apiserver-builder-alpha commit: 95dca1d34e91d6e76c50fa4f272a77f573fd7558
apiserver-boot version: Version: version.Version{ApiserverBuilderVersion:"v1.18.0", KubernetesVendor:"kubernetes-1.18.4", GitCommit:"d5fdf8c1b65a7c6068806b540998889ec5114c36", BuildDate:"2020-06-24-19:17:37", GoOs:"darwin", GoArch:"amd64"}

**Comment by yue9944882** [comment]
> example/kine failed

we removed code-generators from this project. you need to run `controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."` to do a minimal code-generation.

> example/podexec

extending arbitrary subresource is not yet supported in the new framework, but we will be getting it very soon

**Comment by l-qing** [comment]
> > example/kine failed
> 
> we removed code-generators from this project. you need to run `controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."` to do a minimal code-generation.
> 
> > example/podexec
> 
> extending arbitrary subresource is not yet supported in the new framework, but we will be getting it very soon

Thank you for your reply.

**Comment by drewwells** [comment]
The examples do not work even with code generation. `server.StartApiServerWithOptions` was removed

Are the examples built as part of a PR build?
