### ISSUE TITLE
Failed to build the api-server by using the apiserver-boot 

### ISSUE THREAD

**Issue by kinderyj** [kubernetes-sigs/apiserver-builder-alpha#572]
1)
mkdir $GOPATH/src/github.com/test/demo-apiserver

cd $GOPATH/src/github.com/test/demo-apiserver

curl -o boilerplate.go.txt https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.go.txt

apiserver-boot init repo --domain test.me

apiserver-boot create group version resource --group demo --version v1beta1 --non-namespaced=true --kind Foo

apiserver-boot create subresource --subresource bar --group demo --version v1beta1 --kind Foo

apiserver-boot build generated

error occurred:
go: sigs.k8s.io/apiserver-builder-alpha@v1.18.0 requires
	github.com/kubernetes-incubator/reference-docs@v0.0.0: reading github.com/kubernetes-incubator/reference-docs/go.mod at revision v0.0.0: unknown revision v0.0.0

2)Try to use go mod:
go mod init
go mod tidy
Got the same error:
go: sigs.k8s.io/apiserver-builder-alpha@v1.18.0 requires
	github.com/kubernetes-incubator/reference-docs@v0.0.0: reading github.com/kubernetes-incubator/reference-docs/go.mod at revision v0.0.0: unknown revision v0.0.0

**Comment by clarkmcc** [comment]
What's the output of go env?

**Comment by nfrush** [comment]
I'm getting the same error.
