### ISSUE TITLE
[question] how to add more command line parameters

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes-sigs/apiserver-builder-alpha#584]
hello, I'm writing an apiserver with a custom storage. I need to be able to add a few more command line parameters to initialize the custom storage. What is the best way to do it? 
apiserver-builder seems to be using cobra, but I am not sure how to append the parameters I need to the list it already creates.

**Comment by yue9944882** [comment]
@raffaelespazzoli are you already using [apiserver-runtime](https://github.com/kubernetes-sigs/apiserver-runtime)? if that is the case, you can add flags to the cobra commands e.g. `cobra.Command#Flags()`

**Comment by raffaelespazzoli** [comment]
I'm afraid I don't fully get the questsion, I'm starting my server like this:
```
	err := builder.APIServer.
		WithResourceAndHandler(&redhatcopv1alpha1.SecretEngine{}, vaultstorage.NewVaultMountStorageProvider()). // namespaced resource
		WithLocalDebugExtension().
		//WithOpenAPIDefinitions("vault.redhatcop.redhat.io", "v1alpha1", redhatcopv1alpha1.GetOpenAPIDefinitions).
		Execute()
```
I see the apiserver-runtime being imported in the import list.
I saw that cobra was being used, can you make an example of how to add new parameters to the cobra.Command embedded in the apiserver?

**Comment by yue9944882** [comment]
@raffaelespazzoli sure, if you navigate into the implementation of `Execute()` at the end of the builder flow, you will find that that is exactly where we're creating a cobra.Command instance. in order to add flags, you can do sth like the following code instead:

```go
	cmd, err := builder.APIServer.
		WithResourceAndHandler(&redhatcopv1alpha1.SecretEngine{}, vaultstorage.NewVaultMountStorageProvider()). // namespaced resource
		WithLocalDebugExtension().
		//WithOpenAPIDefinitions("vault.redhatcop.redhat.io", "v1alpha1", redhatcopv1alpha1.GetOpenAPIDefinitions).
		Build()
       cmd.Flags().... // TODO: add ur flag here
       err = cmd.Execute()

```

**Comment by raffaelespazzoli** [comment]
I am not able to make this approach work, probably because I am unfamiliar with Flags. here is what I am doing:
```golang
	cmd.Flags().AddFlag(&pflag.Flag{
		Name:     vaultstorage.KubeAuthPathFlagName,
		Usage:    "this is the path where the kubernetes authentication method was mounted",
		DefValue: "auth/kubernetes",
	})
	viper.BindPFlag(vaultstorage.KubeAuthPathFlagName, cmd.PersistentFlags().Lookup(vaultstorage.KubeAuthPathFlagName))
	err = cmd.Execute()
```
I am getting a segfault on the last line:
```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x119c4bc]

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).Set(0xc000130e00, 0x1efe33e, 0x23, 0x7ffdcda5dc91, 0xf, 0x7ffdcda5dc6d, 0xc0004fe750)
	/home/rspazzol/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:463 +0xbc
github.com/spf13/pflag.(*FlagSet).Parse.func1(0xc0004fde00, 0x7ffdcda5dc91, 0xf, 0x23, 0xc0004fe800)
	/home/rspazzol/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:1138 +0x54
github.com/spf13/pflag.(*FlagSet).parseLongArg(0xc000130e00, 0x7ffdcda5dc6b, 0x35, 0xc00004c0e0, 0x0, 0x0, 0xc000527cc8, 0xc00004c0e0, 0x1, 0x1, ...)
	/home/rspazzol/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:1000 +0x295
```
any idea of what the problem might be?

**Comment by raffaelespazzoli** [comment]
I was actually able to make this work. We can close this.
