### ISSUE TITLE
v2.0.0-beta code generators don't seem to run

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes-sigs/apiserver-builder-alpha#594]
hello I'm trying the v2.0.0-beta binary.
when I run the `build executables`, I get the following:
```bash
apiserver-boot build executables
I0512 09:04:33.840176  855280 build_executables.go:180] CGO_ENABLED=0
I0512 09:04:33.840208  855280 build_executables.go:190] go build -o bin/apiserver cmd/apiserver/main.go
# github.com/redhat-cop/vault-apiserver2/pkg/apis/vault/v1alpha1
pkg/apis/vault/v1alpha1/policy_types.go:64:5: cannot use &Policy{} (type *Policy) as type "sigs.k8s.io/apiserver-runtime/pkg/builder/resource".Object in assignment:
	*Policy does not implement "sigs.k8s.io/apiserver-runtime/pkg/builder/resource".Object (missing DeepCopyObject method)
pkg/apis/vault/v1alpha1/policy_types.go:76:9: cannot use &Policy{} (type *Policy) as type runtime.Object in return argument:
	*Policy does not implement runtime.Object (missing DeepCopyObject method)
... more errors ...
```
This error indicates that the code generators have not run, but from the doc, `build executables` should also run the code generators. The explicit command to run just the code generators I think has been removed.
Any suggestions?

```shell
apiserver-boot version
I0512 09:06:27.162604  856252 version.go:57] Version: version.Version{ApiserverBuilderVersion:"v2.0.0-beta.0", KubernetesVendor:"kubernetes-1.19.2", GitCommit:"v2.0.0-beta.0", BuildDate:"2021-04-19-15:07:43", GoOs:"linux", GoArch:"amd64"}
```

**Comment by zhaoli2333** [comment]
i ran into the same problem

**Comment by erwinvaneyk** [comment]
To fix it manually for now you need to run `make generate` before `apiserver-boot build executables`

**Comment by BenjaminHuang** [comment]
It seems the build generated sub command and apiserver-gen was removed in 3e2c9a9c445b118c3e11e188e57c0997721a9b14.  It'll be appreciated if details of the change reason could be provided.

**Comment by yue9944882** [comment]
the functionalities for doing code-generation is removed from this project b/c [controller-tools](https://github.com/kubernetes-sigs/controller-tools) will a stable alternative working for us to do such thing. plz try the following commands after the installation:

>  $go install sigs.k8s.io/controller-tools/cmd/controller-gen
> $controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."

**Comment by BenjaminHuang** [comment]
> the functionalities for doing code-generation is removed from this project b/c [controller-tools](https://github.com/kubernetes-sigs/controller-tools) will a stable alternative working for us to do such thing. plz try the following commands after the installation:
> 
> > $go install sigs.k8s.io/controller-tools/cmd/controller-gen
> > $controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."

@yue9944882 thanks for the reply,  apiserver-gen can help to generate skaffold code for custom-apiserver, can it be replaced by other tools?

**Comment by yue9944882** [comment]
@BenjaminHuang yes if [conversion-gen|defaulter-gen|openapi-gen] is what you're looking for, you can take a stab at the apiserver-runtime-gen. which is a minimal code generator binary for simplifying the generator's usage:

> $ go install sigs.k8s.io/apiserver-runtime/tools/apiserver-runtime-gen

https://github.com/kubernetes-sigs/apiserver-runtime/tree/main/tools/apiserver-runtime-gen

https://github.com/kubernetes-sigs/apiserver-runtime/blob/0663f60bfee284972294f7d00fdd85c474281fd0/Makefile#L29-L48

**Comment by BenjaminHuang** [comment]
Thanks again for the reply. It's good to see that apiserver-builder reincarnate as apiserver-runtime. I can't wait to give it a try 💯

**Comment by BenjaminHuang** [comment]
suggest migrating apiregister-gen to apiserver-runtime
