### ISSUE TITLE
unknown option -addext

### ISSUE THREAD

**Issue by chenpfeisoo** [kubernetes-sigs/apiserver-builder-alpha#608]
When I execute cmd `apiserver-boot run in-cluster --image=autotest.xxx.com/skai.io/skai-demo:0.0.1 --name=skai-demo --namespace=default` has OpenSSL error
![image](https://user-images.githubusercontent.com/18147157/142979068-baaf476e-1e5f-4312-b14b-49afb9a89c3f.png)

when I check sourcecode ,I find OpenSSL version not checked in function `createCerts`
![image](https://user-images.githubusercontent.com/18147157/142979263-5134fba7-d8c0-40d5-b411-85601044c621.png)

What version should I use here ?

**Comment by Nrehearsal** [comment]
i guess you should update your openssl library```OpenSSL 1.1.1f  31 Mar 2020``` work fine for me
