### ISSUE TITLE
v1.23.0 can not build generate client sdk

### ISSUE THREAD

**Issue by zhenkuang** [kubernetes-sigs/apiserver-builder-alpha#633]
v1.23.0 can not spport the commend "apiserver-boot build generate" to generate client sdk

**Comment by Wang-Kai** [comment]
> v1.23.0 can not spport the commend "apiserver-boot build generate" to generate client sdk

Have you solve the problem ? I met the same issue.

**Comment by zhenkuang** [comment]
> > v1.23.0 can not spport the commend "apiserver-boot build generate" to generate client sdk
> 
> Have you solve the problem ? I met the same issue.

you can use kubebuilder to generate client sdk alone.
