### ISSUE TITLE
failed to install through "go install"

### ISSUE THREAD

**Issue by FingerLiu** [kubernetes-sigs/apiserver-builder-alpha#643]
`go install sigs.k8s.io/apiserver-builder-alpha/cmd/apiserver-boot@v2.0.0-beta.0` gives me error:

```
go: sigs.k8s.io/apiserver-builder-alpha/cmd/apiserver-boot@v2.0.0-beta.0: sigs.k8s.io/apiserver-builder-alpha@v2.0.0-beta.0: invalid version: module contains a go.mod file, so module path must match major version ("sigs.k8s.io/apiserver-builder-alpha/v2")
```

but ` go install sigs.k8s.io/apiserver-builder-alpha/cmd/apiserver-boot@v1.23.0` works

**Comment by liangyuanpeng** [comment]
Seems like have revert  v2 

https://github.com/kubernetes-sigs/apiserver-builder-alpha/commit/3e39b4615484f54b8b5174d451e78028a831e20f
