### ISSUE TITLE
Where is the unversioned API

### ISSUE THREAD

**Issue by JackyZhangFuDan** [kubernetes-sigs/apiserver-builder-alpha#646]
Hello Expert,

I have a question about the generated aggregated API server source code. I had added two versions to my aggregated server via the builder, and the server was built and ran locally successfully, but I can't find the 'unversioned' API source code under package 'pkg/apis/<my group>', although the other (external) versions were shown there as sub-folders. 

Could you please hint where can I see that unversioned (also called as internal version) API?

thank you very much,
Jacky

**Comment by markzhang0928** [comment]
the same question here. Btw, will this project be kept up-to-date with new k8s versions?
